version: "3.9"

services:
  web:
    build: .
    container_name: fashion-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_IMAGES: ${S3_BUCKET_IMAGES}
      S3_BUCKET_DOCUMENTS: ${S3_BUCKET_DOCUMENTS}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - .:/backend/app
